---
virtualmachines:
  - name: "rhel"
    image: "rhel-10-2-eus-06-08-26"
    memory: "4G"
    cores: 1
    packages:
      - tmux
    image_size: "40G"
    register_satellite: false
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
