---
virtualmachines:
  - name: "rhel"
    image: "rhel-9-4-05-27-24"
    bootloader: efi
    memory: "4G"
    cores: 1
    packages:
      - tmux
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
