---
virtualmachines:
  - name: "rhel"
    image: "rhel-9.6"
    memory: "4G"
    cores: 1
    packages:
      - tmux
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
